description: Northwest Territories cost of living tax credit threshold for middle income person
values:
  2022-12-31: 12_000
metadata:
  unit: currency-CAD
  label: Northwest Territories cost of living tax credit threshold for middle income person
  reference:
  - title: Government of Canada - Credit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years/general-income-tax-benefit-package/northwest-territories/5012-tc.html 
