description: Northwest Territories living tax credit high income base
values:
  2022-12-31: 48_000
metadata:
  unit: currency-CAD
  label: Northwest Territories living tax credit high income base
  reference:
  - title: Government of Canada - Credit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years/general-income-tax-benefit-package/northwest-territories/5012-tc.html 